/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const maintenancetasks_Logic = require('./code/maintenancetasks-logic');
class jouleSrv extends LCAPApplicationService {
    async init() {
        this.on(['CREATE', 'UPDATE'], 'MaintenanceTasks', async (request, next) => {

            
            
            return maintenancetasks_Logic(request, next);
        });
        return super.init();
    }
}
module.exports = {
    jouleSrv
};